/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSightingArgs } from "./CreateSightingArgs";
import { UpdateSightingArgs } from "./UpdateSightingArgs";
import { DeleteSightingArgs } from "./DeleteSightingArgs";
import { SightingFindManyArgs } from "./SightingFindManyArgs";
import { SightingFindUniqueArgs } from "./SightingFindUniqueArgs";
import { Sighting } from "./Sighting";
import { SightingService } from "../sighting.service";

@graphql.Resolver(() => Sighting)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SightingResolverBase {
  constructor(
    protected readonly service: SightingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "read",
    possession: "any",
  })
  async _sightingsMeta(
    @graphql.Args() args: SightingFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Sighting])
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "read",
    possession: "any",
  })
  async sightings(
    @graphql.Args() args: SightingFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sighting[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Sighting",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Sighting, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "read",
    possession: "own",
  })
  async sighting(
    @graphql.Args() args: SightingFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sighting | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Sighting",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Sighting)
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "create",
    possession: "any",
  })
  async createSighting(
    @graphql.Args() args: CreateSightingArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sighting> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Sighting",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Sighting"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sighting)
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "update",
    possession: "any",
  })
  async updateSighting(
    @graphql.Args() args: UpdateSightingArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sighting | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Sighting",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Sighting"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sighting)
  @nestAccessControl.UseRoles({
    resource: "Sighting",
    action: "delete",
    possession: "any",
  })
  async deleteSighting(
    @graphql.Args() args: DeleteSightingArgs
  ): Promise<Sighting | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
