/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Sighting } from "@prisma/client";

export class SightingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.SightingFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingFindManyArgs>
  ): Promise<number> {
    return this.prisma.sighting.count(args);
  }

  async findMany<T extends Prisma.SightingFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingFindManyArgs>
  ): Promise<Sighting[]> {
    return this.prisma.sighting.findMany(args);
  }
  async findOne<T extends Prisma.SightingFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingFindUniqueArgs>
  ): Promise<Sighting | null> {
    return this.prisma.sighting.findUnique(args);
  }
  async create<T extends Prisma.SightingCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingCreateArgs>
  ): Promise<Sighting> {
    return this.prisma.sighting.create<T>(args);
  }
  async update<T extends Prisma.SightingUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingUpdateArgs>
  ): Promise<Sighting> {
    return this.prisma.sighting.update<T>(args);
  }
  async delete<T extends Prisma.SightingDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SightingDeleteArgs>
  ): Promise<Sighting> {
    return this.prisma.sighting.delete(args);
  }
}
