/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SightingWhereInput } from "./SightingWhereInput";
import { Type } from "class-transformer";
import { SightingOrderByInput } from "./SightingOrderByInput";

@ArgsType()
class SightingFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => SightingWhereInput,
  })
  @Field(() => SightingWhereInput, { nullable: true })
  @Type(() => SightingWhereInput)
  where?: SightingWhereInput;

  @ApiProperty({
    required: false,
    type: SightingOrderByInput,
  })
  @Field(() => SightingOrderByInput, { nullable: true })
  @Type(() => SightingOrderByInput)
  orderBy?: SightingOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { SightingFindManyArgs };
